global:
  scrape_interval: 15s # How often to scrape targets by default

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:5000"]

  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:3000"]
