version: '3.8'

services:
  backend:
    build:
      context: ./containers/backend-rampi
    container_name: backend
    networks:
      - internal_network
      - bridged_network
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./containers/frontend
      args:
        REACT_APP_BACKEND_URL: "http://backend:5000/ram"
    container_name: frontend
    networks:
      - internal_network
      - bridged_network
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000/ram

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - internal_network
      - bridged_network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./containers/grafana/provisioning:/etc/grafana/provisioning # Mount provisioning directory
      - ./containers/grafana/dashboards:/var/lib/grafana/dashboards # Mount dashboards directory

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - internal_network
      - bridged_network
    volumes:
      - prometheus_data:/prometheus
      - ./containers/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

networks:
  bridged_network:
    driver: bridge
  internal_network:
    driver: bridge
    internal: true

volumes:
  grafana_data:
  prometheus_data:
