version: '3.8'

services:
  backend:
    build:
      context: ./backend-rampi
    container_name: backend
    networks:
      - internal_network
      - bridged_network
    ports:
      - "5000:5000" # Expose backend on host for browser access
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: "http://localhost:5000/ram" # Pass backend URL
    container_name: frontend
    networks:
      - internal_network
      - bridged_network
    ports:
      - "3000:3000" # Expose frontend on host
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000/ram # Updated Backend URL

networks:
  bridged_network:
    driver: bridge
  internal_network:
    driver: bridge
    internal: true
